### ISSUE TITLE
GTS Ingest: updated dataset links for WQB-04 and WQB-05

### ISSUE THREAD

**Issue by pacioos** [ioos/ioos-netcdf#41]
Hi ioos-metadata,
I wanted to point out a small update that is needed on your [gold-standard-examples](https://github.com/ioos/ioos-metadata/blob/gh-pages/_docs/gold-standard-examples.md) page. We are honored to have the PacIOOS **WQB-04** and **WQB-05** buoys listed as example datasets under the **GTS Ingest** category. Due to ERDDAP requirements, however, we needed to rename our dataset identifiers without the use of dashes. Thus, these were renamed to **wqb_04** and **wqb_05** back in Nov 2022, and their urls have changed accordingly:

https://pae-paha.pacioos.hawaii.edu/erddap/info/wqb_04/index.html
https://pae-paha.pacioos.hawaii.edu/erddap/info/wqb_05/index.html

Can you please update these links on your page? Many thanks!
Aloha,
John Maurer
Data System Engineer
Pacific Islands Ocean Observing System (PacIOOS)
University of Hawaii at Manoa

**Comment by ocefpaf** [comment]
Done in #42. Thanks for the report!
